// Dashboard Overview Data
export const overviewData = {
  kpis: [
    { title: "Revenue Today", value: "$3,450", change: "+12%", trend: "up" },
    { title: "Occupancy Rate", value: "78%", change: "+5%", trend: "up" },
    { title: "Active Reservations", value: "42", change: "-3%", trend: "down" },
    { title: "Room Service Orders", value: "16", change: "+8%", trend: "up" },
    { title: "Staff on Duty", value: "24", change: "0%", trend: "neutral" },
  ],
  revenueData: [
    { date: "Jan", revenue: 12000 },
    { date: "Feb", revenue: 15000 },
    { date: "Mar", revenue: 18000 },
    { date: "Apr", revenue: 16000 },
    { date: "May", revenue: 21000 },
    { date: "Jun", revenue: 28000 },
    { date: "Jul", revenue: 32000 },
    { date: "Aug", revenue: 36000 },
    { date: "Sep", revenue: 30000 },
    { date: "Oct", revenue: 25000 },
    { date: "Nov", revenue: 22000 },
    { date: "Dec", revenue: 28000 },
  ],
  occupancyData: [
    { date: "Jan", occupancy: 65 },
    { date: "Feb", occupancy: 70 },
    { date: "Mar", occupancy: 75 },
    { date: "Apr", occupancy: 72 },
    { date: "May", occupancy: 78 },
    { date: "Jun", occupancy: 85 },
    { date: "Jul", occupancy: 92 },
    { date: "Aug", occupancy: 95 },
    { date: "Sep", occupancy: 88 },
    { date: "Oct", occupancy: 82 },
    { date: "Nov", occupancy: 78 },
    { date: "Dec", occupancy: 85 },
  ],
  alerts: [
    { type: "success", message: "All systems operational", time: "Just now" },
    { type: "warning", message: "Room 302 maintenance scheduled", time: "10 min ago" },
    { type: "error", message: "Overbooking detected for July 15-17", time: "1 hour ago" },
  ],
  timeline: [
    { time: "08:00 AM", event: "Check-out", room: "Room 105", guest: "Sarah Johnson" },
    { time: "10:30 AM", event: "Check-in", room: "Room 210", guest: "Michael Brown" },
    { time: "12:00 PM", event: "Check-out", room: "Room 315", guest: "David Wilson" },
    { time: "02:00 PM", event: "Check-in", room: "Room 105", guest: "Emily Davis" },
    { time: "04:30 PM", event: "Check-in", room: "Room 422", guest: "Robert Miller" },
  ],
}

// Bookings Data
export const bookingsData = {
  bookings: [
    {
      id: "B1001",
      guest: "John Smith",
      room: "301",
      checkIn: "2023-07-10",
      checkOut: "2023-07-15",
      status: "Confirmed",
      source: "Direct",
      payment: "Paid",
      amount: "$1,250",
    },
    {
      id: "B1002",
      guest: "Sarah Johnson",
      room: "105",
      checkIn: "2023-07-08",
      checkOut: "2023-07-10",
      status: "Checked Out",
      source: "Booking.com",
      payment: "Paid",
      amount: "$450",
    },
    {
      id: "B1003",
      guest: "Michael Brown",
      room: "210",
      checkIn: "2023-07-10",
      checkOut: "2023-07-12",
      status: "Checked In",
      source: "Expedia",
      payment: "Paid",
      amount: "$380",
    },
    {
      id: "B1004",
      guest: "Emily Davis",
      room: "105",
      checkIn: "2023-07-10",
      checkOut: "2023-07-14",
      status: "Confirmed",
      source: "Direct",
      payment: "Partial",
      amount: "$800",
    },
    {
      id: "B1005",
      guest: "Robert Miller",
      room: "422",
      checkIn: "2023-07-10",
      checkOut: "2023-07-13",
      status: "Confirmed",
      source: "Airbnb",
      payment: "Pending",
      amount: "$650",
    },
  ],
  upcomingCheckIns: 12,
  upcomingCheckOuts: 8,
  cancellations: 3,
  noShows: 1,
}

// Rooms Data
export const roomsData = {
  roomStatus: [
    { room: "101", type: "Standard", status: "Occupied", guest: "Thomas Wilson", checkOut: "Jul 12" },
    { room: "102", type: "Standard", status: "Clean", guest: null, checkOut: null },
    { room: "103", type: "Standard", status: "Dirty", guest: null, checkOut: null },
    { room: "104", type: "Standard", status: "Maintenance", guest: null, checkOut: null },
    { room: "105", type: "Standard", status: "Occupied", guest: "Emily Davis", checkOut: "Jul 14" },
    { room: "201", type: "Deluxe", status: "Clean", guest: null, checkOut: null },
    { room: "202", type: "Deluxe", status: "Occupied", guest: "James Anderson", checkOut: "Jul 11" },
    { room: "203", type: "Deluxe", status: "Dirty", guest: null, checkOut: null },
    { room: "204", type: "Deluxe", status: "Clean", guest: null, checkOut: null },
    { room: "205", type: "Deluxe", status: "Occupied", guest: "Lisa Thompson", checkOut: "Jul 13" },
    { room: "301", type: "Suite", status: "Occupied", guest: "John Smith", checkOut: "Jul 15" },
    { room: "302", type: "Suite", status: "Maintenance", guest: null, checkOut: null },
    { room: "303", type: "Suite", status: "Clean", guest: null, checkOut: null },
    { room: "304", type: "Suite", status: "Occupied", guest: "William Brown", checkOut: "Jul 12" },
    { room: "305", type: "Suite", status: "Clean", guest: null, checkOut: null },
  ],
  inventory: [
    { item: "Bath Towels", stock: 120, reorderLevel: 50, status: "Adequate" },
    { item: "Hand Towels", stock: 150, reorderLevel: 60, status: "Adequate" },
    { item: "Toilet Paper", stock: 80, reorderLevel: 40, status: "Adequate" },
    { item: "Shampoo", stock: 95, reorderLevel: 50, status: "Adequate" },
    { item: "Conditioner", stock: 90, reorderLevel: 50, status: "Adequate" },
    { item: "Body Wash", stock: 85, reorderLevel: 50, status: "Adequate" },
    { item: "Soap Bars", stock: 110, reorderLevel: 60, status: "Adequate" },
    { item: "Slippers", stock: 45, reorderLevel: 40, status: "Low" },
    { item: "Bathrobes", stock: 35, reorderLevel: 30, status: "Low" },
    { item: "Dental Kits", stock: 25, reorderLevel: 30, status: "Critical" },
  ],
}

// Restaurant Data
export const restaurantData = {
  activeOrders: [
    {
      id: "O1001",
      type: "Room Service",
      room: "301",
      items: "Club Sandwich, French Fries, Coke",
      time: "10 min ago",
      status: "Preparing",
    },
    {
      id: "O1002",
      type: "Restaurant",
      table: "5",
      items: "Caesar Salad, Grilled Salmon, White Wine",
      time: "15 min ago",
      status: "Served",
    },
    {
      id: "O1003",
      type: "Room Service",
      room: "210",
      items: "Burger, Onion Rings, Beer",
      time: "5 min ago",
      status: "Preparing",
    },
    {
      id: "O1004",
      type: "Restaurant",
      table: "8",
      items: "Pasta Carbonara, Garlic Bread, Tiramisu",
      time: "20 min ago",
      status: "Served",
    },
    {
      id: "O1005",
      type: "Room Service",
      room: "422",
      items: "Breakfast Platter, Orange Juice, Coffee",
      time: "Just now",
      status: "New",
    },
  ],
  popularItems: [
    { item: "Club Sandwich", orders: 42, revenue: "$630" },
    { item: "Burger", orders: 38, revenue: "$570" },
    { item: "Caesar Salad", orders: 35, revenue: "$525" },
    { item: "Pasta Carbonara", orders: 30, revenue: "$450" },
    { item: "Grilled Salmon", orders: 28, revenue: "$700" },
    { item: "Breakfast Platter", orders: 25, revenue: "$375" },
    { item: "Pizza Margherita", orders: 22, revenue: "$330" },
    { item: "Steak", orders: 20, revenue: "$800" },
  ],
  salesByCategory: [
    { category: "Main Course", sales: 12500 },
    { category: "Appetizers", sales: 5800 },
    { category: "Desserts", sales: 4200 },
    { category: "Beverages", sales: 7500 },
    { category: "Alcohol", sales: 9800 },
  ],
}

// Payments Data
export const paymentsData = {
  transactions: [
    {
      id: "T1001",
      guest: "John Smith",
      amount: "$1,250",
      date: "Jul 10, 2023",
      method: "Credit Card",
      status: "Completed",
    },
    {
      id: "T1002",
      guest: "Sarah Johnson",
      amount: "$450",
      date: "Jul 8, 2023",
      method: "ZifyPay",
      status: "Completed",
    },
    { id: "T1003", guest: "Michael Brown", amount: "$380", date: "Jul 10, 2023", method: "UPI", status: "Completed" },
    {
      id: "T1004",
      guest: "Emily Davis",
      amount: "$400",
      date: "Jul 10, 2023",
      method: "Credit Card",
      status: "Partial",
    },
    { id: "T1005", guest: "Robert Miller", amount: "$650", date: "Jul 10, 2023", method: "ZifyPay", status: "Pending" },
    { id: "T1006", guest: "Jennifer Wilson", amount: "$120", date: "Jul 9, 2023", method: "Cash", status: "Completed" },
    {
      id: "T1007",
      guest: "David Thompson",
      amount: "$850",
      date: "Jul 9, 2023",
      method: "Credit Card",
      status: "Completed",
    },
    { id: "T1008", guest: "Lisa Anderson", amount: "$75", date: "Jul 10, 2023", method: "UPI", status: "Completed" },
  ],
  paymentMethods: [
    { method: "Credit Card", percentage: 45 },
    { method: "ZifyPay", percentage: 25 },
    { method: "UPI", percentage: 15 },
    { method: "Cash", percentage: 10 },
    { method: "Other", percentage: 5 },
  ],
  revenueBySource: [
    { source: "Direct Bookings", amount: 25000 },
    { source: "Booking.com", amount: 18000 },
    { source: "Expedia", amount: 15000 },
    { source: "Airbnb", amount: 12000 },
    { source: "Others", amount: 8000 },
  ],
}

// Housekeeping Data
export const housekeepingData = {
  tasks: [
    { id: "H1001", room: "101", type: "Cleaning", assignedTo: "Maria Garcia", status: "Completed", time: "08:30 AM" },
    { id: "H1002", room: "103", type: "Cleaning", assignedTo: "Maria Garcia", status: "Pending", time: "10:00 AM" },
    {
      id: "H1003",
      room: "203",
      type: "Cleaning",
      assignedTo: "Carlos Rodriguez",
      status: "In Progress",
      time: "09:15 AM",
    },
    {
      id: "H1004",
      room: "302",
      type: "Maintenance",
      assignedTo: "Robert Johnson",
      status: "In Progress",
      time: "11:00 AM",
    },
    {
      id: "H1005",
      room: "104",
      type: "Maintenance",
      assignedTo: "Robert Johnson",
      status: "Pending",
      time: "01:30 PM",
    },
    { id: "H1006", room: "205", type: "Inspection", assignedTo: "Susan Miller", status: "Pending", time: "02:00 PM" },
    { id: "H1007", room: "303", type: "Cleaning", assignedTo: "Carlos Rodriguez", status: "Pending", time: "11:30 AM" },
    { id: "H1008", room: "204", type: "Inspection", assignedTo: "Susan Miller", status: "Completed", time: "09:45 AM" },
  ],
  maintenanceTickets: [
    {
      id: "M1001",
      room: "302",
      issue: "AC not working",
      priority: "High",
      status: "In Progress",
      reported: "Jul 10, 09:15 AM",
    },
    {
      id: "M1002",
      room: "104",
      issue: "Leaking faucet",
      priority: "Medium",
      status: "Pending",
      reported: "Jul 10, 08:30 AM",
    },
    {
      id: "M1003",
      room: "201",
      issue: "TV remote broken",
      priority: "Low",
      status: "Resolved",
      reported: "Jul 9, 02:45 PM",
    },
    {
      id: "M1004",
      room: "305",
      issue: "Wifi connectivity issues",
      priority: "Medium",
      status: "Resolved",
      reported: "Jul 9, 11:20 AM",
    },
    {
      id: "M1005",
      room: "102",
      issue: "Light bulb replacement",
      priority: "Low",
      status: "Pending",
      reported: "Jul 10, 10:10 AM",
    },
  ],
  cleaningProgress: {
    total: 15,
    cleaned: 5,
    pending: 8,
    inProgress: 2,
  },
}

// Staff Data
export const staffData = {
  staff: [
    { id: "S1001", name: "Maria Garcia", role: "Housekeeping", status: "On Duty", performance: 95, shift: "Morning" },
    {
      id: "S1002",
      name: "Carlos Rodriguez",
      role: "Housekeeping",
      status: "On Duty",
      performance: 88,
      shift: "Morning",
    },
    { id: "S1003", name: "Robert Johnson", role: "Maintenance", status: "On Duty", performance: 92, shift: "Morning" },
    {
      id: "S1004",
      name: "Susan Miller",
      role: "Housekeeping Supervisor",
      status: "On Duty",
      performance: 97,
      shift: "Morning",
    },
    { id: "S1005", name: "James Wilson", role: "Front Desk", status: "On Duty", performance: 90, shift: "Morning" },
    { id: "S1006", name: "Jennifer Brown", role: "Front Desk", status: "Off Duty", performance: 85, shift: "Evening" },
    { id: "S1007", name: "Michael Davis", role: "Restaurant", status: "On Duty", performance: 89, shift: "Morning" },
    { id: "S1008", name: "Lisa Thompson", role: "Restaurant", status: "Off Duty", performance: 91, shift: "Evening" },
    { id: "S1009", name: "David Anderson", role: "Maintenance", status: "Off Duty", performance: 86, shift: "Night" },
    { id: "S1010", name: "Sarah Johnson", role: "Front Desk", status: "Off Duty", performance: 93, shift: "Night" },
  ],
  performanceByRole: [
    { role: "Housekeeping", performance: 90 },
    { role: "Maintenance", performance: 89 },
    { role: "Front Desk", performance: 92 },
    { role: "Restaurant", performance: 87 },
    { role: "Management", performance: 95 },
  ],
  staffByShift: {
    morning: 12,
    evening: 8,
    night: 4,
  },
}

// Reports Data
export const reportsData = {
  occupancyTrend: [
    { month: "Jan", occupancy: 65 },
    { month: "Feb", occupancy: 70 },
    { month: "Mar", occupancy: 75 },
    { month: "Apr", occupancy: 72 },
    { month: "May", occupancy: 78 },
    { month: "Jun", occupancy: 85 },
    { month: "Jul", occupancy: 92 },
    { month: "Aug", occupancy: 95 },
    { month: "Sep", occupancy: 88 },
    { month: "Oct", occupancy: 82 },
    { month: "Nov", occupancy: 78 },
    { month: "Dec", occupancy: 85 },
  ],
  revenueByRoomType: [
    { type: "Standard", revenue: 45000 },
    { type: "Deluxe", revenue: 65000 },
    { type: "Suite", revenue: 85000 },
    { type: "Executive", revenue: 55000 },
  ],
  guestFeedback: [
    { category: "Cleanliness", rating: 4.5 },
    { category: "Service", rating: 4.7 },
    { category: "Amenities", rating: 4.2 },
    { category: "Food", rating: 4.6 },
    { category: "Value", rating: 4.3 },
    { category: "Location", rating: 4.8 },
  ],
  availableReports: [
    { name: "Monthly Revenue Report", format: "PDF/CSV", lastGenerated: "Jul 1, 2023" },
    { name: "Occupancy Analysis", format: "PDF/CSV", lastGenerated: "Jun 30, 2023" },
    { name: "Staff Performance Report", format: "PDF", lastGenerated: "Jun 15, 2023" },
    { name: "Guest Feedback Summary", format: "PDF", lastGenerated: "Jun 30, 2023" },
    { name: "Inventory Status Report", format: "CSV", lastGenerated: "Jul 5, 2023" },
  ],
}

// Marketing Data
export const marketingData = {
  campaigns: [
    { id: "C1001", name: "Summer Special", type: "Email", status: "Active", sent: 1500, opened: 750, conversion: 120 },
    { id: "C1002", name: "Weekend Getaway", type: "SMS", status: "Active", sent: 1000, opened: 800, conversion: 95 },
    {
      id: "C1003",
      name: "Loyalty Rewards",
      type: "Email",
      status: "Completed",
      sent: 2000,
      opened: 950,
      conversion: 180,
    },
    {
      id: "C1004",
      name: "Restaurant Promotion",
      type: "Social Media",
      status: "Active",
      sent: 5000,
      opened: 3200,
      conversion: 250,
    },
    { id: "C1005", name: "Corporate Package", type: "Email", status: "Draft", sent: 0, opened: 0, conversion: 0 },
  ],
  guestSegments: [
    { segment: "Frequent Guests", count: 250, averageSpend: "$850", loyaltyPoints: "High" },
    { segment: "Business Travelers", count: 420, averageSpend: "$650", loyaltyPoints: "Medium" },
    { segment: "Families", count: 180, averageSpend: "$950", loyaltyPoints: "Medium" },
    { segment: "Couples", count: 320, averageSpend: "$750", loyaltyPoints: "Low" },
    { segment: "One-time Guests", count: 580, averageSpend: "$550", loyaltyPoints: "None" },
  ],
  promoCodePerformance: [
    { code: "SUMMER23", redemptions: 85, revenue: "$12,750", discount: "15%" },
    { code: "WEEKEND", redemptions: 65, revenue: "$9,750", discount: "10%" },
    { code: "LOYAL10", redemptions: 120, revenue: "$18,000", discount: "10%" },
    { code: "DINE20", redemptions: 95, revenue: "$4,750", discount: "20%" },
    { code: "CORP15", redemptions: 40, revenue: "$16,000", discount: "15%" },
  ],
}

// Settings Data
export const settingsData = {
  userRoles: [
    { role: "Admin", count: 2, permissions: "Full Access" },
    { role: "Manager", count: 5, permissions: "Limited Admin" },
    { role: "Staff", count: 18, permissions: "Operational Access" },
    { role: "Receptionist", count: 8, permissions: "Front Desk Only" },
    { role: "Restaurant", count: 12, permissions: "Restaurant Only" },
  ],
  integrations: [
    { name: "Booking.com", status: "Connected", lastSync: "10 min ago" },
    { name: "Expedia", status: "Connected", lastSync: "15 min ago" },
    { name: "Airbnb", status: "Connected", lastSync: "30 min ago" },
    { name: "QuickBooks", status: "Connected", lastSync: "1 hour ago" },
    { name: "Xero", status: "Disconnected", lastSync: "N/A" },
    { name: "Stripe", status: "Connected", lastSync: "5 min ago" },
    { name: "Mailchimp", status: "Connected", lastSync: "2 hours ago" },
  ],
}




export const mockRooms: Room[] = [
  {
    id: 1,
    number: "101",
    floor: 1,
    type: "Standard",
    beds: "1 King",
    price: 129.99,
    status: "Available",
  },
  {
    id: 2,
    number: "102",
    floor: 1,
    type: "Standard",
    beds: "2 Queens",
    price: 149.99,
    status: "Occupied",
  },
  {
    id: 3,
    number: "103",
    floor: 1,
    type: "Deluxe",
    beds: "1 King",
    price: 179.99,
    status: "Cleaning",
  },
  {
    id: 4,
    number: "104",
    floor: 1,
    type: "Suite",
    beds: "1 King + Sofa",
    price: 249.99,
    status: "Maintenance",
  },
  {
    id: 5,
    number: "201",
    floor: 2,
    type: "Standard",
    beds: "2 Queens",
    price: 159.99,
    status: "Available",
  },
  {
    id: 6,
    number: "202",
    floor: 2,
    type: "Deluxe",
    beds: "1 King",
    price: 189.99,
    status: "Occupied",
  },
  {
    id: 7,
    number: "203",
    floor: 2,
    type: "Suite",
    beds: "1 King + Sofa",
    price: 259.99,
    status: "Available",
  },
  {
    id: 8,
    number: "204",
    floor: 2,
    type: "Standard",
    beds: "2 Queens",
    price: 149.99,
    status: "Cleaning",
  },
  {
    id: 9,
    number: "301",
    floor: 3,
    type: "Deluxe",
    beds: "1 King",
    price: 199.99,
    status: "Available",
  },
  {
    id: 10,
    number: "302",
    floor: 3,
    type: "Suite",
    beds: "1 King + Sofa",
    price: 279.99,
    status: "Occupied",
  },
  {
    id: 11,
    number: "303",
    floor: 3,
    type: "Penthouse",
    beds: "1 King + 2 Queens",
    price: 399.99,
    status: "Available",
  },
  {
    id: 12,
    number: "304",
    floor: 3,
    type: "Deluxe",
    beds: "2 Queens",
    price: 189.99,
    status: "Maintenance",
  },
]
